# Generated by Django 4.2.5 on 2024-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("matricula", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
