# Generated by Django 4.2.5 on 2024-03-21 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estudante", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estagio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_termino", models.DateField(blank=True, null=True)),
                ("carga_horaria", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_protocolo", models.DateTimeField(auto_now_add=True)),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudante.estudante",
                    ),
                ),
                (
                    "protocolado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
